#!/usr/bin/env bash
# Build an .rpm so Minecraft Hub for Linux installs like a normal app (menu + search) on
# the Fedora-based gaming distributions users asked for — Nobara, Bazzite and
# plain Fedora (issue #156).
# Usage: scripts/build-rpm.sh      -> dist/minecraft-hub-<ver>-1.x86_64.rpm
set -euo pipefail

SRC="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
VER="$(grep -m1 '^VERSION = ' "$SRC/minecrafthub/config.py" | cut -d'"' -f2)"
OUT="$SRC/dist"
# rpmbuild empties %{buildroot} itself before %install, so the payload is
# staged beside it and copied in by the spec rather than pre-installed there.
PKG="$OUT/rpm-stage"
TOP="$OUT/rpmbuild"
SOURCE_DATE_EPOCH="${SOURCE_DATE_EPOCH:-1782250551}"
[[ "$SOURCE_DATE_EPOCH" =~ ^[0-9]+$ ]] || {
  echo "SOURCE_DATE_EPOCH must be a non-negative integer" >&2
  exit 1
}
export SOURCE_DATE_EPOCH

command -v rpmbuild >/dev/null || {
  echo "rpmbuild missing (Fedora: sudo dnf install rpm-build;" \
       "Debian/Ubuntu: sudo apt install rpm)" >&2
  exit 1
}

# RPM's Version field must not contain '-'; a tagged release never does, but a
# hand-edited config.py could, and rpmbuild would only fail much later.
[[ "$VER" =~ ^[0-9A-Za-z.+~]+$ ]] || {
  echo "VERSION '$VER' cannot be an RPM version (no '-' allowed)" >&2
  exit 1
}

rm -rf "$PKG" "$TOP"
mkdir -p "$OUT" \
  "$TOP/BUILD" "$TOP/RPMS" "$TOP/SPECS" \
  "$PKG/usr/lib/minecraft-hub/data" \
  "$PKG/usr/bin" \
  "$PKG/usr/share/applications" \
  "$PKG/usr/share/icons/hicolor/256x256/apps" \
  "$PKG/usr/share/doc/minecraft-hub" \
  "$PKG/usr/share/licenses/minecraft-hub"

[[ -f "$SRC/data/icon.png" ]] || { echo "data/icon.png missing" >&2; exit 1; }

install -m755 "$SRC/minecraft-hub" "$PKG/usr/lib/minecraft-hub/minecraft-hub"
cp -r "$SRC/bol"                       "$PKG/usr/lib/minecraft-hub/bol"
# Bundle the GUI toolkit (PySide6-Essentials + shiboken6, packaging, and
# python-xlib — none of these are distribution dependencies) next to bol/ so
# it's on sys.path. cryptography stays a distribution dependency.
# python-xlib (+ six) provides structured RandR monitor geometry; bol.x11
# falls back to the xrandr CLI without it.
# Hash-pinned, wheels only, no sdist builds. The closure is the same one the
# .deb installs, so both distribution packages share its SHA-256 list in
# third_party/requirements-deb.txt (--require-hashes rejects any mismatch).
python3 -m pip install --quiet --no-cache-dir --no-compile --no-deps \
  --require-hashes --only-binary=:all: --target \
  "$PKG/usr/lib/minecraft-hub" \
  -r "$SRC/third_party/requirements-deb.txt"
rm -rf "$PKG/usr/lib/minecraft-hub"/bin 2>/dev/null || true
find "$PKG/usr/lib/minecraft-hub" -name __pycache__ -type d -exec rm -rf {} +
for metadata in \
  "$PKG/usr/lib/minecraft-hub/shiboken6-6.9.3.dist-info" \
  "$PKG/usr/lib/minecraft-hub/pyside6_essentials-6.9.3.dist-info" \
  "$PKG/usr/lib/minecraft-hub/packaging-26.2.dist-info" \
  "$PKG/usr/lib/minecraft-hub/python_xlib-0.33.dist-info" \
  "$PKG/usr/lib/minecraft-hub/six-1.17.0.dist-info"; do
  [[ -d "$metadata" ]] || {
    echo "missing pinned dependency metadata: $metadata" >&2
    exit 1
  }
  dependency_license="$(
    find "$metadata" -type f -iname 'LICENSE*' -print -quit
  )"
  # Some wheels (shiboken6, pyside6-essentials) carry no bundled LICENSE
  # file at all -- Qt for Python states the license only in METADATA's
  # License: field. Accept that as proof the license was reviewed and
  # recorded, rather than requiring a file upstream never ships.
  if [[ -z "$dependency_license" ]]; then
    grep -qE '^License(-Expression)?:' "$metadata/METADATA" 2>/dev/null || {
      echo "missing dependency licence in $metadata" >&2
      exit 1
    }
  fi
done
install -m644 "$SRC/data/icon.png"    "$PKG/usr/lib/minecraft-hub/data/icon.png"
# Relative, unlike the .deb's absolute link: rpm flags an absolute symlink as a
# packaging defect because it cannot be verified inside a buildroot.
ln -s ../lib/minecraft-hub/minecraft-hub "$PKG/usr/bin/minecraft-hub"
install -m644 "$SRC/data/icon.png" \
  "$PKG/usr/share/icons/hicolor/256x256/apps/minecraft-hub.png"
install -m644 "$SRC/data/minecraft-hub.desktop" \
  "$PKG/usr/share/applications/minecraft-hub.desktop"
install -m644 "$SRC/README.md" "$PKG/usr/share/doc/minecraft-hub/README.md"
install -m644 "$SRC/LICENSE" "$PKG/usr/share/licenses/minecraft-hub/LICENSE"

# Wheel archives occasionally carry host-specific modes or Finder metadata.
# Package payloads should be stable and readable regardless of the build host.
find "$PKG" -type f -name '.DS_Store' -delete
find "$PKG" -type d -exec chmod 0755 {} +
find "$PKG" -type f -exec chmod 0644 {} +
chmod 0755 "$PKG/usr/lib/minecraft-hub/minecraft-hub"
find "$PKG" -exec touch -h -d "@$SOURCE_DATE_EPOCH" {} +

SPEC="$TOP/SPECS/minecraft-hub.spec"
cat > "$SPEC" <<EOF
# Generated by scripts/build-rpm.sh — the payload is staged by that script, so
# this spec only packages a finished buildroot.
%global debug_package %{nil}
%global __os_install_post %{nil}
%global _build_id_links none
# Reproducibility: take the build time and clamp every payload mtime from
# SOURCE_DATE_EPOCH instead of "now", so the same checkout yields the same rpm.
%global source_date_epoch_from_changelog 0
%global use_source_date_epoch_as_buildtime 1
%global clamp_mtime_to_source_date_epoch 1

Name:           minecraft-hub
Version:        ${VER}
Release:        1
Summary:        Run Minecraft Bedrock (Windows GDK) on Linux, multiplayer included
License:        MIT
URL:            https://github.com/esteban-dcp/minecraft-hub-linux

# The payload is pure Python plus pinned pure-Python wheels; the launcher is
# only meaningful where the managed engine and the game exist, so the package
# stays x86_64 rather than noarch. Dependencies are declared below and never
# guessed: the bundled wheels' dist-info would otherwise generate requires on
# distribution packages that do not exist.
AutoReqProv:    no
Requires:       python3 >= 3.9
Requires:       python3-cryptography
Requires:       tar
Requires:       zstd
Requires:       xdg-utils
Requires:       /usr/bin/xrandr
Requires:       ca-certificates
Requires:       (curl or wget)
# The GUI toolkit is a vendored PySide6 wheel, so the Qt libraries themselves
# ship inside the package -- but Qt's xcb platform plugin dlopen()s against the
# host's X stack, and every entry below is a hard DT_NEEDED of the bundled
# libqxcb.so (libEGL comes from libQt6Gui). Missing one does not raise in
# Python: Qt aborts natively with "could not load the Qt platform plugin xcb"
# before control returns, so the launcher's own error reporting never runs.
# Regenerate against the pinned wheel with:
#   readelf -d --wide .../PySide6/Qt/plugins/platforms/libqxcb.so | grep NEEDED
# Declared by soname rather than by package name on purpose: with AutoReqProv
# off these are exactly what rpm's own generator would have produced, and the
# packages carrying them are named differently on Fedora (xcb-util-wm,
# xcb-util-cursor, ...) than on openSUSE or Mageia. The soname is the one name
# every RPM distribution agrees on.
Requires:       libglib-2.0.so.0()(64bit)
Requires:       libgthread-2.0.so.0()(64bit)
Requires:       libdbus-1.so.3()(64bit)
Requires:       libfontconfig.so.1()(64bit)
Requires:       libfreetype.so.6()(64bit)
Requires:       libGL.so.1()(64bit)
Requires:       libEGL.so.1()(64bit)
Requires:       libX11.so.6()(64bit)
Requires:       libX11-xcb.so.1()(64bit)
Requires:       libxkbcommon.so.0()(64bit)
Requires:       libxkbcommon-x11.so.0()(64bit)
Requires:       libxcb.so.1()(64bit)
Requires:       libxcb-cursor.so.0()(64bit)
Requires:       libxcb-icccm.so.4()(64bit)
Requires:       libxcb-image.so.0()(64bit)
Requires:       libxcb-keysyms.so.1()(64bit)
Requires:       libxcb-randr.so.0()(64bit)
Requires:       libxcb-render.so.0()(64bit)
Requires:       libxcb-render-util.so.0()(64bit)
Requires:       libxcb-shape.so.0()(64bit)
Requires:       libxcb-shm.so.0()(64bit)
Requires:       libxcb-sync.so.1()(64bit)
Requires:       libxcb-util.so.1()(64bit)
Requires:       libxcb-xfixes.so.0()(64bit)
Requires:       libxcb-xkb.so.1()(64bit)
# xodus-cli opens the Microsoft Store sign-in in an embedded webview.
Requires:       webkit2gtk4.1
Recommends:     mesa-vulkan-drivers

%description
One graphical launcher that downloads a reviewed WineGDK-based GDK-Proton,
provides native Microsoft/Xbox identity, and enables Friends, Servers,
Realms and file imports without a Minecraft process-memory patcher.
Sign-in is direct (no relay or proxy).
No game files are shipped; you supply your own.

%prep

%build

%install
cp -a ${PKG}/. %{buildroot}/

%post
update-desktop-database -q /usr/share/applications 2>/dev/null || :
gtk-update-icon-cache -q -t /usr/share/icons/hicolor 2>/dev/null || :

%postun
update-desktop-database -q /usr/share/applications 2>/dev/null || :
gtk-update-icon-cache -q -t /usr/share/icons/hicolor 2>/dev/null || :

%files
/usr/lib/minecraft-hub
/usr/bin/minecraft-hub
/usr/share/applications/minecraft-hub.desktop
/usr/share/icons/hicolor/256x256/apps/minecraft-hub.png
%dir /usr/share/doc/minecraft-hub
/usr/share/doc/minecraft-hub/README.md
%dir /usr/share/licenses/minecraft-hub
/usr/share/licenses/minecraft-hub/LICENSE
EOF

# --target keeps the architecture explicit instead of inheriting the build
# host's, and _buildhost keeps the recorded hostname out of the package.
LOG="$TOP/rpmbuild.log"
if ! rpmbuild -bb \
    --target x86_64 \
    --define "_topdir $TOP" \
    --define "_buildhost minecraft-hub" \
    "$SPEC" >"$LOG" 2>&1; then
  echo "rpmbuild failed — last 40 lines:" >&2
  tail -n 40 "$LOG" >&2
  exit 1
fi

RPM="$OUT/minecraft-hub-${VER}-1.x86_64.rpm"
BUILT="$TOP/RPMS/x86_64/minecraft-hub-${VER}-1.x86_64.rpm"
[[ -f "$BUILT" ]] || { echo "rpmbuild produced no $BUILT" >&2; exit 1; }
mv -f "$BUILT" "$RPM"
rm -rf "$PKG" "$TOP"
echo "Built: $RPM"
rpm -qip --nosignature "$RPM" | sed -n '1,12p'
echo "Install:  sudo dnf install $RPM     (or: sudo rpm -i $RPM)"
